-- MySQL Script generated by MySQL Workbench
-- Mon Jun 24 22:51:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cancheros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cancheros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cancheros` DEFAULT CHARACTER SET utf8mb3 ;
USE `cancheros` ;



-- -----------------------------------------------------
-- Table `cancheros`.`cancha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`cancha` (
  `id_cancha` INT NOT NULL,
  `cancha_zonal` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cancha`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`tipo_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`tipo_documento` (
  `id_documento` INT NOT NULL,
  `nombre_tipo_documento` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_documento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`rol` (
  `id_rol` INT NOT NULL,
  `nombre_rol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`usuario` (
  `id_usuario` INT NOT NULL,
  `nombre_apellido` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` INT NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `numero_documento` INT NULL DEFAULT NULL,
  `id_rol` INT NULL DEFAULT NULL,
  `id_documento` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `id_rol` (`id_rol` ASC) INVISIBLE,
  INDEX `fk_usuario_tipodocumento` (`id_documento` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipodocumento`
    FOREIGN KEY (`id_documento`)
    REFERENCES `cancheros`.`tipo_documento` (`id_documento`),
  CONSTRAINT `FkRolUser`
    FOREIGN KEY (`id_rol`)
    REFERENCES `cancheros`.`rol` (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`reserva` (
  `id_reserva` INT NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `num_jugadores` INT NULL DEFAULT NULL,
  `petos` INT NULL DEFAULT NULL,
  `balones` INT NULL DEFAULT NULL,
  `id_deporte` INT NULL DEFAULT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_reserva`),
  INDEX `id_deporte` (`id_deporte` ASC) VISIBLE,
  INDEX `fk_usuario_reserva` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_reserva`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `cancheros`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`cancha_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`cancha_reserva` (
  `id_cancha_reserva` INT NOT NULL,
  `id_reserva` INT NULL DEFAULT NULL,
  `id_cancha` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_cancha_reserva`),
  INDEX `id_cancha_idx` (`id_cancha` ASC) VISIBLE,
  INDEX `fk_reserva` (`id_reserva` ASC) VISIBLE,
  CONSTRAINT `fk_cancha`
    FOREIGN KEY (`id_cancha`)
    REFERENCES `cancheros`.`cancha` (`id_cancha`),
  CONSTRAINT `fk_reserva`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `cancheros`.`reserva` (`id_reserva`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`django_admin_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`django_admin_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME(6) NOT NULL,
  `object_id` LONGTEXT NULL DEFAULT NULL,
  `object_repr` VARCHAR(200) NOT NULL,
  `action_flag` SMALLINT UNSIGNED NOT NULL,
  `change_message` LONGTEXT NOT NULL,
  `content_type_id` INT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `django_admin_log_content_type_id_c4bce8eb_fk_django_co` (`content_type_id` ASC) VISIBLE,
  INDEX `django_admin_log_user_id_c564eba6_fk_auth_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `django_admin_log_content_type_id_c4bce8eb_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `cancheros`.`django_content_type` (`id`),
  CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `cancheros`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`django_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`django_migrations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `app` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `applied` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`django_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`django_session` (
  `session_key` VARCHAR(40) NOT NULL,
  `session_data` LONGTEXT NOT NULL,
  `expire_date` DATETIME(6) NOT NULL,
  PRIMARY KEY (`session_key`),
  INDEX `django_session_expire_date_a5c62663` (`expire_date` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`home_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`home_rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`home_tipo_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`home_tipo_documento` (
  `id_documento` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo_documento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_documento`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`home_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`home_usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre_apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(254) NOT NULL,
  `numero_documento` INT NOT NULL,
  `id_documento_id` INT NOT NULL,
  `id_rol_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `home_usuario_id_documento_id_8c5b8792_fk_home_tipo` (`id_documento_id` ASC) VISIBLE,
  INDEX `home_usuario_id_rol_id_73b328a4_fk_home_rol_id_rol` (`id_rol_id` ASC) VISIBLE,
  CONSTRAINT `home_usuario_id_documento_id_8c5b8792_fk_home_tipo`
    FOREIGN KEY (`id_documento_id`)
    REFERENCES `cancheros`.`home_tipo_documento` (`id_documento`),
  CONSTRAINT `home_usuario_id_rol_id_73b328a4_fk_home_rol_id_rol`
    FOREIGN KEY (`id_rol_id`)
    REFERENCES `cancheros`.`home_rol` (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`tipo_deporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`tipo_deporte` (
  `id_deporte` INT NOT NULL,
  `nombre_deporte` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_deporte`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
