# Generated by Django 5.0.6 on 2024-06-24 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancha_zonal', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
                ('num_jugadores', models.IntegerField()),
                ('petos', models.IntegerField()),
                ('balones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_documento',
            fields=[
                ('idTipoDocumento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_documento', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_deporte', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='CanchaReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cancha')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.reserva')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_deporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipodeporte'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=254)),
                ('numero_documento', models.IntegerField()),
                ('id_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipo_documento')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.rol')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usuario'),
        ),
    ]
