# Generated by Django 5.0.6 on 2024-08-03 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cancha',
            table='cancha',
        ),
        migrations.AlterModelTable(
            name='canchareserva',
            table='cancha_reserva',
        ),
        migrations.AlterModelTable(
            name='reserva',
            table='reserva',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='rol',
        ),
        migrations.AlterModelTable(
            name='tipodeporte',
            table='tipo_deporte',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
