-- MySQL Script generated by MySQL Workbench
-- Mon Jun  3 19:46:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cancheros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cancheros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cancheros` DEFAULT CHARACTER SET utf8mb3 ;
USE `cancheros` ;

-- -----------------------------------------------------
-- Table `cancheros`.`auth_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`auth_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`django_content_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`django_content_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `django_content_type_app_label_model_76bd3d3b_uniq` (`app_label` ASC, `model` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`auth_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`auth_permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content_type_id` INT NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_permission_content_type_id_codename_01ab375a_uniq` (`content_type_id` ASC, `codename` ASC) VISIBLE,
  CONSTRAINT `auth_permission_content_type_id_2f476e4b_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `cancheros`.`django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`auth_group_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`auth_group_permissions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_group_permissions_group_id_permission_id_0cd325b0_uniq` (`group_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `cancheros`.`auth_permission` (`id`),
  CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `cancheros`.`auth_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`auth_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`auth_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME(6) NULL DEFAULT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `first_name` VARCHAR(150) NOT NULL,
  `last_name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `is_staff` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `date_joined` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`auth_user_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`auth_user_groups` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_groups_user_id_group_id_94350c0c_uniq` (`user_id` ASC, `group_id` ASC) VISIBLE,
  INDEX `auth_user_groups_group_id_97559544_fk_auth_group_id` (`group_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `cancheros`.`auth_group` (`id`),
  CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `cancheros`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`auth_user_user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`auth_user_user_permissions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_user_permissions_user_id_permission_id_14a6b632_uniq` (`user_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `cancheros`.`auth_permission` (`id`),
  CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `cancheros`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`cancha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`cancha` (
  `id_cancha` INT NOT NULL,
  `cancha_zonal` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cancha`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`rol` (
  `id_rol` INT NOT NULL,
  `nombre_rol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`usuario` (
  `id_usuario` INT NOT NULL,
  `nombre_apellido` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` INT NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `id_documento` INT NULL DEFAULT NULL,
  `numero_documento` INT NULL DEFAULT NULL,
  `id_rol` INT NULL DEFAULT NULL,
  `id_reserva` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `id_documento` (`id_documento` ASC) INVISIBLE,
  INDEX `id_rol` (`id_rol` ASC) INVISIBLE,
  INDEX `id_reserva` (`id_reserva` ASC) VISIBLE,
  CONSTRAINT `FKRolUser`
    FOREIGN KEY (`id_rol`)
    REFERENCES `cancheros`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`reserva` (
  `id_reserva` INT NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `hora` DATETIME NULL DEFAULT NULL,
  `num_jugadores` INT NULL DEFAULT NULL,
  `petos` INT NULL DEFAULT NULL,
  `balones` INT NULL DEFAULT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  `id_deporte` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_reserva`),
  INDEX `id_deporte` (`id_deporte` ASC) VISIBLE,
  CONSTRAINT `id_reserva`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `cancheros`.`usuario` (`id_reserva`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`cancha_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`cancha_reserva` (
  `id_cancha_reserva` INT NOT NULL,
  `id_reserva` INT NULL DEFAULT NULL,
  `id_cancha` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_cancha_reserva`),
  INDEX `id_cancha_idx` (`id_cancha` ASC) VISIBLE,
  INDEX `fk_reserva` (`id_reserva` ASC) VISIBLE,
  CONSTRAINT `fk_cancha`
    FOREIGN KEY (`id_cancha`)
    REFERENCES `cancheros`.`cancha` (`id_cancha`),
  CONSTRAINT `fk_reserva`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `cancheros`.`reserva` (`id_reserva`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`django_admin_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`django_admin_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME(6) NOT NULL,
  `object_id` LONGTEXT NULL DEFAULT NULL,
  `object_repr` VARCHAR(200) NOT NULL,
  `action_flag` SMALLINT UNSIGNED NOT NULL,
  `change_message` LONGTEXT NOT NULL,
  `content_type_id` INT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `django_admin_log_content_type_id_c4bce8eb_fk_django_co` (`content_type_id` ASC) VISIBLE,
  INDEX `django_admin_log_user_id_c564eba6_fk_auth_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `django_admin_log_content_type_id_c4bce8eb_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `cancheros`.`django_content_type` (`id`),
  CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `cancheros`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`django_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`django_migrations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `app` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `applied` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`django_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`django_session` (
  `session_key` VARCHAR(40) NOT NULL,
  `session_data` LONGTEXT NOT NULL,
  `expire_date` DATETIME(6) NOT NULL,
  PRIMARY KEY (`session_key`),
  INDEX `django_session_expire_date_a5c62663` (`expire_date` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`tipo _documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`tipo _documento` (
  `id_documento` INT NOT NULL,
  `nombre_tipo_documento` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_documento`),
  CONSTRAINT `id_documento`
    FOREIGN KEY (`id_documento`)
    REFERENCES `cancheros`.`usuario` (`id_documento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cancheros`.`tipo_deporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancheros`.`tipo_deporte` (
  `id_deporte` INT NOT NULL,
  `nombre_deporte` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_deporte`),
  CONSTRAINT `id_deporte`
    FOREIGN KEY (`id_deporte`)
    REFERENCES `cancheros`.`reserva` (`id_deporte`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
